# Generated by Django 2.1.3 on 2018-11-10 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=64)),
                ('pay_password', models.CharField(max_length=64)),
                ('loyalty', models.IntegerField()),
                ('vips', models.SmallIntegerField()),
                ('adress_id', models.IntegerField()),
                ('head', models.ImageField(default='', upload_to='')),
                ('ex_password', models.SmallIntegerField()),
                ('wallet', models.IntegerField()),
                ('phone', models.CharField(max_length=11)),
                ('wechat', models.CharField(max_length=12)),
                ('qq', models.CharField(max_length=10)),
                ('add_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='xf_Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress', models.CharField(max_length=200)),
                ('uid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wode.User')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='uid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wode.User'),
        ),
    ]
