# Generated by Django 2.1.3 on 2018-11-10 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=20)),
                ('msq', models.IntegerField()),
                ('price', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('describe', models.CharField(max_length=120)),
                ('img', models.ImageField(default='', upload_to='')),
                ('praise', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=120)),
                ('starting_price', models.IntegerField()),
                ('dist_price', models.IntegerField()),
                ('seller_phhoto', models.ImageField(default='', upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='food',
            name='business_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shouye.Seller'),
        ),
    ]
