# Generated by Django 2.1.3 on 2018-11-10 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('content', models.CharField(max_length=288)),
                ('author', models.CharField(max_length=20)),
                ('datas', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
